name: Install and Build
on:
  pull_request:
    branches:
      - master
jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Packages
        run:
          npm ci

      - name: Production Build
        run: 
          npm run build